const SUPABASE_URL='https://vznsvcotzurgmkmtvapm.supabase.co';
const SUPABASE_KEY='sb_publishable_eN8imVSNAXwp8-K9N3mbZw_ZJX0klU8';
const STORE_KEY='holioo_pwa_state_v1';
let sb=null,currentUser=null,deferredInstallPrompt=null,currentView='home',currentCourseId=null,currentSectionId=null,currentSessionId=null,currentBatch=null,currentLibrary={step:'years',year:null,course:null,section:null,item:null};
let cameraStream=null,cameraTrack=null,captureIds=[],cameraFacing='environment',torchOn=false,zoomValue=1;
const app=document.getElementById('app'),toastEl=document.getElementById('toast'),offlineBanner=document.getElementById('offlineBanner');
const uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const stateDefault=()=>({profile:{displayName:'Étudiant',holiooId:'',university:'Sorbonne Université',faculty:'Sciences & Ingénierie',program:'EEA',level:'L2',semester:'S3',academicYear:'2026–2027',publicProfile:false},courses:[{id:uid(),name:'VHDL',color:'#8C5CF5',sections:[]},{id:uid(),name:'Mathématiques',color:'#506BFF',sections:[]},{id:uid(),name:'Électronique',color:'#FF9E42',sections:[]}],inbox:[],files:[]});
let state=loadState();state.courses.forEach(ensureDefaultSections);saveState();

function loadState(){try{const x=JSON.parse(localStorage.getItem(STORE_KEY)||'null');return x?{...stateDefault(),...x}:stateDefault()}catch{return stateDefault()}}
function saveState(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
function ensureDefaultSections(course){course.sections=Array.isArray(course.sections)?course.sections:[];for(const n of ['CM','TD','TP'])if(!course.sections.some(s=>s.name===n))course.sections.push({id:uid(),name:n,type:n,sessions:[]})}
function showToast(msg){toastEl.textContent=msg;toastEl.classList.remove('hidden');setTimeout(()=>toastEl.classList.add('hidden'),2600)}
function setNav(view){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===view))}
function colorForSection(name){return name==='CM'?'#506BFF':name==='TD'?'#8C5CF5':name==='TP'?'#FF9E42':'#29ADB5'}
function iconLetter(name){return(name||'?').slice(0,1).toUpperCase()}
function formatDate(v){try{return new Date(v).toLocaleDateString('fr-FR',{day:'2-digit',month:'short'})}catch{return''}}
let dbPromise;
function db(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('holioo-db',2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('photos'))d.createObjectStore('photos',{keyPath:'id'});if(!d.objectStoreNames.contains('files'))d.createObjectStore('files',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise}
async function dbPut(store,obj){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).put(obj);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function dbGet(store,id){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbDelete(store,id){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).delete(id);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function photoUrl(id){const p=await dbGet('photos',id);return p?.blob?URL.createObjectURL(p.blob):''}
async function blobToDataURL(blob){return await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=()=>rej(f.error);f.readAsDataURL(blob)})}

async function bootstrapCloud(){
  if(!window.supabase)return;
  try{
    const deviceId=localStorage.getItem('holioo_device_id')||`${crypto.randomUUID()}-${Date.now()}`;localStorage.setItem('holioo_device_id',deviceId);
    const r=await fetch(`${SUPABASE_URL}/functions/v1/device-bootstrap`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({device_id:deviceId})});
    const data=await r.json();if(!r.ok)throw new Error(data.error||'Connexion cloud impossible');
    sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
    await sb.auth.setSession({access_token:data.access_token,refresh_token:data.refresh_token});currentUser=data.user;
    const {data:profile}=await sb.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();
    if(profile){state.profile={...state.profile,displayName:profile.name||profile.display_name||state.profile.displayName,holiooId:profile.holioo_id||state.profile.holiooId,university:profile.university||state.profile.university,faculty:profile.faculty||state.profile.faculty,program:profile.program||state.profile.program,level:profile.level||state.profile.level,semester:profile.semester||state.profile.semester,academicYear:profile.academic_year||state.profile.academicYear,publicProfile:!!(profile.public_profile||profile.is_public)};saveState()}
    else{
      const hid=`h${currentUser.id.replace(/-/g,'').slice(0,10)}`;state.profile.holiooId=hid;saveState();
      await sb.from('profiles').insert({id:currentUser.id,user_id:currentUser.id,holioo_id:hid,name:state.profile.displayName,display_name:state.profile.displayName,university:state.profile.university,faculty:state.profile.faculty,program:state.profile.program,level:state.profile.level,semester:state.profile.semester,academic_year:state.profile.academicYear,public_profile:false,is_public:false});
    }
    sb.channel('public-materials-live').on('postgres_changes',{event:'*',schema:'public',table:'public_materials'},()=>{if(currentView==='library')render()}).subscribe();
  }catch(e){console.error(e);showToast('Mode local actif — synchronisation dès le retour d’Internet')}
}

function navigate(view,payload={}){
  if(view!=='capture')stopCamera();currentView=view;
  if(payload.courseId)currentCourseId=payload.courseId;if(payload.sectionId)currentSectionId=payload.sectionId;if(payload.sessionId)currentSessionId=payload.sessionId;
  setNav(['home','courses','capture','library','files'].includes(view)?view:'');render();
}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n){e.preventDefault();navigate(n.dataset.nav)}});

function header(title,sub=''){return `<h1 class="page-title">${esc(title)}</h1>${sub?`<p class="subtitle">${esc(sub)}</p>`:''}`}
function courseCard(c){const count=c.sections.reduce((a,s)=>a+(s.sessions?.length||0),0);return `<button class="card row card-button" data-course="${c.id}"><span class="course-icon" style="background:${c.color||'#506BFF'}">${esc(iconLetter(c.name))}</span><span class="grow"><span class="title">${esc(c.name)}</span><span class="meta">${count} séance${count>1?'s':''} • CM / TD / TP</span></span><span class="chev">›</span></button>`}
function bindCourseCards(){document.querySelectorAll('[data-course]').forEach(b=>b.addEventListener('click',()=>{currentCourseId=b.dataset.course;navigate('course')}))}

function renderHome(){
  app.innerHTML=`${header('Bonjour 👋','Capturez maintenant. Organisez après le cours.')}<button class="card quick-capture card-button" data-nav="capture"><span class="quick-icon">●</span><span class="grow"><span class="title">Capture rapide</span><span class="meta">Aucune question avant la photo</span></span><span class="chev">›</span></button><div class="section-title">Vos cours</div><div class="grid">${state.courses.slice(0,3).map(courseCard).join('')}</div><div class="section-title">À reprendre</div>${state.inbox.length?`<button class="card row card-button" id="openInbox"><span class="section-icon" style="background:#FF9E42">I</span><span class="grow"><span class="title">Inbox</span><span class="meta">${state.inbox.reduce((a,b)=>a+b.photoIds.length,0)} photos à organiser</span></span><span class="chev">›</span></button>`:`<div class="card empty">Votre Inbox est vide.</div>`}<div class="section-title">Bibliothèque académique</div><button class="card row card-button" data-nav="library"><span class="section-icon" style="background:#29ADB5">B</span><span class="grow"><span class="title">Matériel public</span><span class="meta">Année → cours → CM / TD / TP</span></span><span class="chev">›</span></button>`;
  bindCourseCards();document.getElementById('openInbox')?.addEventListener('click',()=>navigate('inbox'));
}
function renderCourses(){app.innerHTML=`${header('Cours','Chaque cours contient CM, TD, TP et vos sections personnalisées.')}<div class="grid">${state.courses.map(courseCard).join('')}</div><div class="actions"><button class="btn primary full" id="addCourse">+ Ajouter un cours</button></div>`;bindCourseCards();document.getElementById('addCourse').onclick=()=>{const name=prompt('Nom du cours');if(!name)return;state.courses.push({id:uid(),name,color:'#506BFF',sections:[]});ensureDefaultSections(state.courses.at(-1));saveState();render()}}
function renderCourse(){const c=state.courses.find(x=>x.id===currentCourseId);if(!c){navigate('courses');return}ensureDefaultSections(c);saveState();app.innerHTML=`<button class="back" id="back">‹</button>${header(c.name,'Choisissez CM, TD, TP ou une section personnalisée.')}<div class="grid">${c.sections.map(s=>`<button class="card row card-button" data-section="${s.id}"><span class="section-icon" style="background:${colorForSection(s.name)}">${esc(iconLetter(s.name))}</span><span class="grow"><span class="title">${esc(s.name)}</span><span class="meta">${s.sessions.length} séance${s.sessions.length>1?'s':''}</span></span><span class="chev">›</span></button>`).join('')}</div><div class="actions"><button class="btn ghost full" id="addSection">+ Ajouter une section personnalisée</button></div>`;back.onclick=()=>navigate('courses');document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{currentSectionId=b.dataset.section;navigate('section')});addSection.onclick=()=>{const n=prompt('Nom de la section (Projet, Révision, Examen...)');if(!n)return;c.sections.push({id:uid(),name:n,type:'CUSTOM',sessions:[]});saveState();render()}}
function renderSection(){const c=state.courses.find(x=>x.id===currentCourseId),s=c?.sections.find(x=>x.id===currentSectionId);if(!s){navigate('course');return}app.innerHTML=`<button class="back" id="back">‹</button>${header(`${c.name} • ${s.name}`,'Les numéros sont indépendants pour chaque section.')}<div class="grid">${s.sessions.length?s.sessions.map(x=>`<button class="card row card-button" data-session="${x.id}"><span class="section-icon" style="background:${colorForSection(s.name)}">${x.number||'•'}</span><span class="grow"><span class="title">${esc(x.title)}</span><span class="meta">${x.photoIds?.length||0} photos • ${formatDate(x.createdAt)}</span></span><span class="chev">›</span></button>`).join(''):`<div class="card empty">Aucune séance pour le moment.</div>`}</div><div class="actions"><button class="btn purple full" id="newSession">+ Nouvelle séance</button></div>`;back.onclick=()=>navigate('course');document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{currentSessionId=b.dataset.session;navigate('session')});newSession.onclick=()=>{const num=(s.sessions.at(-1)?.number||0)+1;const custom=prompt('Nom de la séance (facultatif)');const title=custom?.trim()||`${s.name} ${num}`;const session={id:uid(),number:num,title,photoIds:[],createdAt:now(),visibility:'private'};s.sessions.push(session);saveState();currentSessionId=session.id;navigate('session')}}
function findSession(){const course=state.courses.find(x=>x.id===currentCourseId),section=course?.sections.find(x=>x.id===currentSectionId),session=section?.sessions.find(x=>x.id===currentSessionId);return course&&section&&session?{course,section,session}:null}
async function renderSession(){const ctx=findSession();if(!ctx){navigate('courses');return}const{course,section,session}=ctx;app.innerHTML=`<button class="back" id="back">‹</button>${header(session.title,`${course.name} • ${section.name} • ${session.photoIds.length} photo${session.photoIds.length>1?'s':''}`)}<div id="sessionThumbs" class="thumbs"></div>${session.photoIds.length?`<div class="actions"><button class="btn primary full" id="pdfBtn">Créer le PDF</button><button class="btn teal full" id="publishBtn">${session.visibility==='public'?'Publié ✓':'Publier cette séance'}</button></div>`:`<div class="card empty">Cette séance ne contient pas encore de photos.</div><div class="actions"><button class="btn orange full" data-nav="capture">Prendre des photos</button></div>`}`;back.onclick=()=>navigate('section');await fillSessionThumbs(session);document.getElementById('pdfBtn')?.addEventListener('click',()=>generatePdf(course,section,session));document.getElementById('publishBtn')?.addEventListener('click',()=>publishSession(course,section,session))}
async function fillSessionThumbs(session){const box=document.getElementById('sessionThumbs');if(!box)return;box.innerHTML='';for(let i=0;i<session.photoIds.length;i++){const id=session.photoIds[i],url=await photoUrl(id),d=document.createElement('div');d.className='thumb';d.innerHTML=`<img src="${url}" alt="Photo ${i+1}"><span class="num">${i+1}</span><div class="thumb-actions"><button data-left="${id}">←</button><button data-right="${id}">→</button><button data-del="${id}">×</button></div>`;box.appendChild(d)}box.querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>movePhoto(session,b.dataset.left,-1));box.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>movePhoto(session,b.dataset.right,1));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteSessionPhoto(session,b.dataset.del))}
function movePhoto(session,id,dir){const i=session.photoIds.indexOf(id),j=i+dir;if(i<0||j<0||j>=session.photoIds.length)return;[session.photoIds[i],session.photoIds[j]]=[session.photoIds[j],session.photoIds[i]];saveState();render()}
async function deleteSessionPhoto(session,id){if(!confirm('Supprimer cette photo ?'))return;session.photoIds=session.photoIds.filter(x=>x!==id);await dbDelete('photos',id);saveState();render()}

function renderCapture(){app.innerHTML=`<div class="capture-screen"><div class="capture-head"><button id="closeCam">×</button><div class="capture-title">Capture rapide</div><span class="badge orange" id="captureCount">0 photo</span></div><div class="camera-stage"><video id="cameraVideo" autoplay playsinline muted></video><div class="camera-message">Aucune sélection de cours maintenant. Continuez à photographier.</div></div><div class="camera-controls"><div class="camera-tools"><button class="tool-btn" id="flipCam">↺ Caméra</button><button class="tool-btn" id="torchBtn">☀ Torche</button><button class="tool-btn" id="galleryBtn">＋ Galerie</button><input type="file" id="galleryInput" accept="image/*" multiple hidden></div><div class="zoom-row"><span>1×</span><input id="zoomRange" type="range" min="1" max="1" step="0.1" value="1"><span id="zoomLabel">1×</span></div><div class="shutter-row"><button class="tool-btn" id="finishCapture">Terminer</button><button class="shutter" id="shutter" aria-label="Prendre une photo"></button><span></span></div></div></div>`;setTimeout(startCamera,0);closeCam.onclick=()=>{stopCamera();navigate('home')};shutter.onclick=capturePhoto;flipCam.onclick=async()=>{cameraFacing=cameraFacing==='environment'?'user':'environment';await startCamera()};torchBtn.onclick=toggleTorch;galleryBtn.onclick=()=>galleryInput.click();galleryInput.onchange=importGallery;finishCapture.onclick=finishCapture;zoomRange.oninput=applyZoom}
async function startCamera(){stopCamera();const v=document.getElementById('cameraVideo');if(!v)return;try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:cameraFacing},width:{ideal:1920},height:{ideal:1080}},audio:false});v.srcObject=cameraStream;cameraTrack=cameraStream.getVideoTracks()[0];const caps=cameraTrack.getCapabilities?.()||{},zr=document.getElementById('zoomRange'),tb=document.getElementById('torchBtn');if(caps.zoom&&zr){zr.min=caps.zoom.min;zr.max=caps.zoom.max;zr.step=caps.zoom.step||.1;zr.value=Math.max(caps.zoom.min,Math.min(1,caps.zoom.max));zoomValue=Number(zr.value);zoomLabel.textContent=`${zoomValue.toFixed(1)}×`}else if(zr){zr.disabled=true;zoomLabel.textContent='Non dispo'}if(tb&&!caps.torch){tb.disabled=true;tb.textContent='Torche indisponible'}}catch(e){console.error(e);showToast('Autorisez la caméra dans Safari')}}
function stopCamera(){cameraStream?.getTracks?.().forEach(t=>t.stop());cameraStream=null;cameraTrack=null;torchOn=false}
async function applyZoom(e){if(!cameraTrack)return;zoomValue=Number(e.target.value);try{await cameraTrack.applyConstraints({advanced:[{zoom:zoomValue}]});zoomLabel.textContent=`${zoomValue.toFixed(1)}×`}catch{}}
async function toggleTorch(){if(!cameraTrack)return;const caps=cameraTrack.getCapabilities?.()||{};if(!caps.torch){showToast('La torche n’est pas disponible dans ce navigateur');return}torchOn=!torchOn;try{await cameraTrack.applyConstraints({advanced:[{torch:torchOn}]});torchBtn.classList.toggle('active',torchOn)}catch{showToast('Impossible d’activer la torche')}}
async function capturePhoto(){const v=cameraVideo;if(!v?.videoWidth){showToast('La caméra n’est pas prête');return}const maxW=1600,scale=Math.min(1,maxW/v.videoWidth),c=document.createElement('canvas');c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);c.getContext('2d').drawImage(v,0,0,c.width,c.height);const blob=await new Promise(res=>c.toBlob(res,'image/jpeg',.86)),id=uid();await dbPut('photos',{id,blob,createdAt:now()});captureIds.push(id);updateCaptureCount();navigator.vibrate?.(20)}
async function importGallery(e){for(const f of [...(e.target.files||[])]){const id=uid();await dbPut('photos',{id,blob:f,createdAt:now()});captureIds.push(id)}updateCaptureCount();e.target.value=''}
function updateCaptureCount(){const e=document.getElementById('captureCount');if(e)e.textContent=`${captureIds.length} photo${captureIds.length>1?'s':''}`}
function finishCapture(){if(!captureIds.length){showToast('Prenez au moins une photo');return}stopCamera();currentBatch={id:uid(),photoIds:[...captureIds],selected:new Set(captureIds),createdAt:now()};captureIds=[];navigate('captured')}

async function fillBatchThumbs(boxId,ids,selectable=true){const box=document.getElementById(boxId);if(!box)return;box.innerHTML='';for(let i=0;i<ids.length;i++){const id=ids[i],u=await photoUrl(id),sel=currentBatch?.selected?.has(id),d=document.createElement('button');d.className=`thumb ${sel?'selected':''}`;d.innerHTML=`<img src="${u}" alt="Photo ${i+1}"><span class="num">${i+1}</span>${selectable?`<span class="check">${sel?'✓':''}</span>`:''}`;if(selectable)d.onclick=()=>{sel?currentBatch.selected.delete(id):currentBatch.selected.add(id);renderOrganize()};box.appendChild(d)}}
async function renderCaptured(){app.innerHTML=`${header(`${currentBatch?.photoIds.length||0} photos capturées`,'Organisez-les maintenant, divisez le lot ou gardez-les dans Inbox.')}<div class="thumbs" id="capturedThumbs"></div><div class="actions"><button class="btn orange full" id="organizeNow">Organiser les photos</button><button class="btn ghost full" id="saveInbox">Enregistrer dans Inbox</button></div>`;await fillBatchThumbs('capturedThumbs',currentBatch?.photoIds||[],false);organizeNow.onclick=()=>navigate('organize');saveInbox.onclick=()=>{state.inbox.unshift({id:currentBatch.id,photoIds:[...currentBatch.photoIds],createdAt:currentBatch.createdAt});saveState();currentBatch=null;showToast('Photos gardées dans Inbox');navigate('home')}}
async function renderOrganize(){if(!currentBatch){navigate('home');return}const course=state.courses.find(c=>c.id===currentCourseId)||state.courses[0];currentCourseId=course.id;ensureDefaultSections(course);const section=course.sections.find(s=>s.id===currentSectionId)||course.sections.find(s=>s.name==='TD');currentSectionId=section.id;const next=(section.sessions.at(-1)?.number||0)+1;app.innerHTML=`${header('Organiser le lot','Sélectionnez les photos pour cette séance. Le reste pourra aller ailleurs.')}<div class="thumbs" id="organizeThumbs"></div><div class="spacer"></div><div class="field"><label>Cours</label><select id="orgCourse">${state.courses.map(c=>`<option value="${c.id}" ${c.id===course.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Section</label><select id="orgSection">${course.sections.map(s=>`<option value="${s.id}" ${s.id===section.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Nom de la séance (facultatif)</label><input id="sessionName" placeholder="${esc(section.name)} ${next}"></div><p class="small">${currentBatch.selected.size} sélectionnée(s) • ${currentBatch.photoIds.length-currentBatch.selected.size} restante(s)</p><div class="actions"><button class="btn purple full" id="assignSelected">Enregistrer les photos sélectionnées</button><button class="btn ghost full" id="selectAll">Tout sélectionner / désélectionner</button></div>`;await fillBatchThumbs('organizeThumbs',currentBatch.photoIds,true);orgCourse.onchange=e=>{currentCourseId=e.target.value;currentSectionId=null;renderOrganize()};orgSection.onchange=e=>{currentSectionId=e.target.value;renderOrganize()};selectAll.onclick=()=>{currentBatch.selected=currentBatch.selected.size===currentBatch.photoIds.length?new Set():new Set(currentBatch.photoIds);renderOrganize()};assignSelected.onclick=()=>assignSelectedPhotos(sessionName.value)}
function assignSelectedPhotos(name){if(!currentBatch.selected.size){showToast('Sélectionnez au moins une photo');return}const c=state.courses.find(x=>x.id===currentCourseId),s=c?.sections.find(x=>x.id===currentSectionId);if(!s)return;const num=(s.sessions.at(-1)?.number||0)+1,title=name.trim()||`${s.name} ${num}`,ids=[...currentBatch.selected],session={id:uid(),number:num,title,photoIds:ids,createdAt:now(),visibility:'private'};s.sessions.push(session);currentSessionId=session.id;currentBatch.photoIds=currentBatch.photoIds.filter(id=>!currentBatch.selected.has(id));currentBatch.selected=new Set(currentBatch.photoIds);saveState();if(currentBatch.photoIds.length){showToast(`${ids.length} photos enregistrées. Organisez le reste.`);renderOrganize()}else{currentBatch=null;navigate('session')}}
async function renderInbox(){app.innerHTML=`${header('Inbox','Les captures non classées restent ici en sécurité.')}<div class="grid" id="inboxList"></div>`;const box=inboxList;if(!state.inbox.length){box.innerHTML='<div class="card empty">Inbox est vide.</div>';return}state.inbox.forEach(b=>{const el=document.createElement('button');el.className='card row card-button';el.innerHTML=`<span class="section-icon" style="background:#FF9E42">${b.photoIds.length}</span><span class="grow"><span class="title">${formatDate(b.createdAt)} • ${b.photoIds.length} photos</span><span class="meta">Non classées</span></span><span class="chev">›</span>`;el.onclick=()=>{currentBatch={...b,selected:new Set(b.photoIds)};state.inbox=state.inbox.filter(x=>x.id!==b.id);saveState();navigate('organize')};box.appendChild(el)})}

async function generatePdf(course,section,session){if(!window.jspdf){showToast('Module PDF indisponible');return}showToast('Création du PDF…');try{const{jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'});doc.setFont('helvetica','bold');doc.setFontSize(24);doc.text(course.name,20,35);doc.setFontSize(16);doc.text(session.title,20,49);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(`${section.name} • ${state.profile.academicYear}`,20,59);doc.setFontSize(15);doc.setFont('helvetica','bold');doc.text('Table des matières',20,82);doc.setFontSize(11);doc.setFont('helvetica','normal');doc.text(`1. ${session.title} ........................ 2`,20,94);let page=2;for(const id of session.photoIds){const p=await dbGet('photos',id);if(!p?.blob)continue;doc.addPage();const data=await blobToDataURL(p.blob),props=doc.getImageProperties(data),ratio=Math.min(170/props.width,245/props.height),w=props.width*ratio,h=props.height*ratio;doc.addImage(data,'JPEG',(210-w)/2,18,w,h,undefined,'FAST');doc.setFontSize(9);doc.text(`${course.name} • ${session.title}`,15,287);doc.text(String(page),195,287,{align:'right'});page++}const blob=doc.output('blob'),fileId=uid(),fileName=`${course.name}-${session.title}.pdf`.replace(/\s+/g,'-');await dbPut('files',{id:fileId,blob,name:fileName,createdAt:now()});state.files.unshift({id:fileId,title:`${course.name} — ${session.title}`,createdAt:now(),pages:page-1});saveState();const file=new File([blob],fileName,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:fileName,files:[file]});else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=fileName;a.click()}showToast('PDF créé')}catch(e){console.error(e);showToast('Erreur pendant la création du PDF')}}
async function renderFiles(){app.innerHTML=`${header('Fichiers','Vos PDF restent sur l’appareil et peuvent être partagés.')}<div class="grid" id="fileList"></div>`;const box=fileList;if(!state.files.length){box.innerHTML='<div class="card empty">Aucun PDF pour le moment.</div>';return}for(const f of state.files){const el=document.createElement('button');el.className='card pdf-card card-button';el.innerHTML=`<span class="pdf-icon">PDF</span><span class="grow"><span class="title">${esc(f.title)}</span><span class="meta">${f.pages||''} pages • ${formatDate(f.createdAt)}</span></span><span class="chev">›</span>`;el.onclick=async()=>{const data=await dbGet('files',f.id);if(!data?.blob)return;const file=new File([data.blob],`${f.title}.pdf`,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]}))navigator.share({files:[file],title:f.title});else window.open(URL.createObjectURL(data.blob),'_blank')};box.appendChild(el)}}

function profilePayload(){return{id:currentUser?.id,user_id:currentUser?.id,holioo_id:state.profile.holiooId,name:state.profile.displayName,display_name:state.profile.displayName,university:state.profile.university,faculty:state.profile.faculty,program:state.profile.program,level:state.profile.level,semester:state.profile.semester,academic_year:state.profile.academicYear,public_profile:state.profile.publicProfile,is_public:state.profile.publicProfile}}
async function syncProfile(){if(sb&&currentUser)await sb.from('profiles').upsert(profilePayload(),{onConflict:'id'})}
function renderProfile(){const p=state.profile;app.innerHTML=`${header('Profil','Le profil académique est facultatif.')}<div class="profile-head"><span class="avatar">${esc(iconLetter(p.displayName))}</span><div class="title">${esc(p.displayName)}</div><div class="meta">@${esc(p.holiooId||'connexion…')}</div><span class="badge ${p.publicProfile?'blue':'green'}">${p.publicProfile?'Profil public':'Profil privé'}</span></div><div class="field"><label>Nom affiché</label><input id="pName" value="${esc(p.displayName)}"></div><div class="field"><label>Université</label><input id="pUni" value="${esc(p.university)}"></div><div class="field"><label>Faculté</label><input id="pFaculty" value="${esc(p.faculty)}"></div><div class="field"><label>Filière / majeure</label><input id="pProgram" value="${esc(p.program)}"></div><div class="grid two"><div class="field"><label>Niveau</label><input id="pLevel" value="${esc(p.level)}"></div><div class="field"><label>Semestre</label><input id="pSemester" value="${esc(p.semester)}"></div></div><div class="field"><label>Année universitaire</label><input id="pYear" value="${esc(p.academicYear)}"></div><label class="card row"><input type="checkbox" id="pPublic" ${p.publicProfile?'checked':''}><span class="grow"><span class="title">Profil public</span><span class="meta">Trouvable uniquement avec l’identifiant Holioo exact.</span></span></label><div class="actions"><button class="btn primary full" id="saveProfile">Enregistrer le profil</button><button class="btn ghost full" id="findId">Rechercher un identifiant Holioo</button><button class="btn ghost full" id="driveBtn">Google Drive — connexion à activer</button></div><div class="notice">Holioo ne propose ni amis, ni abonnements, ni messagerie.</div><div id="profileSearch"></div>`;saveProfile.onclick=async()=>{Object.assign(state.profile,{displayName:pName.value.trim()||'Étudiant',university:pUni.value.trim(),faculty:pFaculty.value.trim(),program:pProgram.value.trim(),level:pLevel.value.trim(),semester:pSemester.value.trim(),academicYear:pYear.value.trim(),publicProfile:pPublic.checked});saveState();await syncProfile();showToast('Profil enregistré');render()};findId.onclick=searchProfileId;driveBtn.onclick=()=>showToast('Google Drive sera activé après l’autorisation OAuth Google')}
async function searchProfileId(){const id=prompt('Identifiant Holioo exact (sans @)');if(!id||!sb)return;const{data}=await sb.from('profiles').select('holioo_id,name,display_name,university,program,level,semester,public_profile,is_public').eq('holioo_id',id.replace('@','')).maybeSingle();profileSearch.innerHTML=data&&(data.public_profile||data.is_public)?`<div class="card" style="margin-top:14px"><div class="title">${esc(data.name||data.display_name||'Étudiant')}</div><div class="meta">@${esc(data.holioo_id)}</div><div class="meta">${esc([data.university,data.program,data.level,data.semester].filter(Boolean).join(' • '))}</div><p class="small">Consultation uniquement — aucune fonction de contact.</p></div>`:`<div class="notice" style="margin-top:14px">Profil introuvable ou privé.</div>`}

async function publishSession(course,section,session){if(session.visibility==='public'){showToast('Cette séance est déjà publique');return}if(!sb||!currentUser){showToast('Connexion cloud nécessaire');return}const p=state.profile;if(!p.university||!p.program||!p.level||!p.semester||!p.academicYear){showToast('Complétez votre profil académique');navigate('profile');return}if(!confirm('Publier cette séance dans la bibliothèque académique ? Vérifiez qu’aucun visage ou renseignement personnel d’une autre personne n’est visible.'))return;showToast('Publication…');try{const paths=[];for(let i=0;i<session.photoIds.length;i++){const ph=await dbGet('photos',session.photoIds[i]);if(!ph?.blob)continue;const path=`${currentUser.id}/${session.id}/${i+1}.jpg`;const{error}=await sb.storage.from('public-materials').upload(path,ph.blob,{contentType:'image/jpeg',upsert:true});if(error)throw error;paths.push(path)}const{error}=await sb.from('public_materials').insert({owner_id:currentUser.id,session_local_id:session.id,title:session.title,type:'Photos',photo_count:paths.length,storage_paths:paths,university:p.university,faculty:p.faculty,program:p.program,level:p.level,semester:p.semester,academic_year:p.academicYear,course:course.name,section:section.name,contributor_name:p.publicProfile?p.displayName:null,contributor_holioo_id:p.publicProfile?p.holiooId:null,is_published:true});if(error)throw error;session.visibility='public';saveState();showToast('Séance publiée');render()}catch(e){console.error(e);showToast('Publication impossible — vérifiez Internet')}}

function libraryQuery(columns='*'){const p=state.profile;return sb.from('public_materials').select(columns).eq('is_published',true).eq('university',p.university).eq('program',p.program).eq('level',p.level).eq('semester',p.semester).eq('academic_year',currentLibrary.year)}
async function renderLibrary(){if(!sb){app.innerHTML=`${header('Bibliothèque académique','Connexion au cloud en cours…')}<div class="card empty">Internet est nécessaire pour le matériel public.</div>`;return}const p=state.profile;
  if(currentLibrary.step==='years'){const{data=[]}=await sb.from('public_materials').select('academic_year').eq('university',p.university).eq('program',p.program).eq('level',p.level).eq('semester',p.semester).eq('is_published',true);const years=[...new Set([p.academicYear,...data.map(x=>x.academic_year).filter(Boolean)])].sort().reverse();app.innerHTML=`${header('Bibliothèque académique','Commencez par l’année universitaire.')}<div class="library-context"><strong>${esc(p.university||'Université')}</strong><span class="meta">${esc([p.program,p.level,p.semester].filter(Boolean).join(' • '))}</span></div><div class="section-title">Années universitaires</div><div class="grid">${years.map(y=>`<button class="card row card-button year-card" data-year="${esc(y)}"><span class="grow"><span class="title">${esc(y)}</span><span class="meta">Voir les cours et le matériel public</span></span><span class="chev">›</span></button>`).join('')}</div>`;document.querySelectorAll('[data-year]').forEach(b=>b.onclick=()=>{currentLibrary={step:'courses',year:b.dataset.year};render()})}
  else if(currentLibrary.step==='courses'){const{data=[]}=await libraryQuery('course'),courses=[...new Set(data.map(x=>x.course))].sort();app.innerHTML=`<button class="back" id="libBack">‹</button>${header(currentLibrary.year,'Cours publics')}<div class="grid">${courses.length?courses.map(c=>`<button class="card row card-button" data-libcourse="${esc(c)}"><span class="course-icon" style="background:#29ADB5">${esc(iconLetter(c))}</span><span class="grow"><span class="title">${esc(c)}</span><span class="meta">Matériel partagé par des étudiants</span></span><span class="chev">›</span></button>`).join(''):'<div class="card empty">Aucun matériel public pour cette année.</div>'}</div>`;libBack.onclick=()=>{currentLibrary={step:'years'};render()};document.querySelectorAll('[data-libcourse]').forEach(b=>b.onclick=()=>{currentLibrary={...currentLibrary,step:'sections',course:b.dataset.libcourse};render()})}
  else if(currentLibrary.step==='sections'){const{data=[]}=await libraryQuery('section').eq('course',currentLibrary.course),sections=[...new Set(data.map(x=>x.section))];app.innerHTML=`<button class="back" id="libBack">‹</button>${header(currentLibrary.course,currentLibrary.year)}<div class="grid">${sections.map(s=>`<button class="card row card-button" data-libsection="${esc(s)}"><span class="section-icon" style="background:${colorForSection(s)}">${esc(iconLetter(s))}</span><span class="grow"><span class="title">${esc(s)}</span><span class="meta">Séances et PDF publics</span></span><span class="chev">›</span></button>`).join('')}</div>`;libBack.onclick=()=>{currentLibrary={...currentLibrary,step:'courses',course:null};render()};document.querySelectorAll('[data-libsection]').forEach(b=>b.onclick=()=>{currentLibrary={...currentLibrary,step:'items',section:b.dataset.libsection};render()})}
  else if(currentLibrary.step==='items'){const{data=[]}=await libraryQuery('*').eq('course',currentLibrary.course).eq('section',currentLibrary.section).order('created_at',{ascending:false});app.innerHTML=`<button class="back" id="libBack">‹</button>${header(`${currentLibrary.course} • ${currentLibrary.section}`,'Matériel public')}<div class="chips"><span class="chip active">Récent</span><span class="chip">Photos</span><span class="chip">PDF</span></div><div class="grid" style="margin-top:12px">${data.length?data.map(i=>`<button class="card row card-button" data-libitem="${i.id}"><span class="section-icon" style="background:#29ADB5">${i.photo_count||0}</span><span class="grow"><span class="title">${esc(i.title)}</span><span class="meta">${i.photo_count||0} photos • ${formatDate(i.created_at)}</span></span><span class="chev">›</span></button>`).join(''):'<div class="card empty">Aucun matériel public ici.</div>'}</div>`;libBack.onclick=()=>{currentLibrary={...currentLibrary,step:'sections',section:null};render()};document.querySelectorAll('[data-libitem]').forEach(b=>b.onclick=()=>{currentLibrary={...currentLibrary,step:'item',item:data.find(x=>x.id===b.dataset.libitem)};render()})}
  else if(currentLibrary.step==='item'){const i=currentLibrary.item;app.innerHTML=`<button class="back" id="libBack">‹</button>${header(i.title,`${i.course} • ${i.section} • ${i.academic_year}`)}<span class="badge teal">PUBLIC</span><div id="publicThumbs" class="thumbs" style="margin-top:14px"></div><p class="small">${i.contributor_name?`Partagé par ${esc(i.contributor_name)}`:'Partagé par un étudiant'}</p><div class="actions"><button class="btn ghost full" id="reportBtn">Signaler ce matériel</button></div>`;libBack.onclick=()=>{currentLibrary={...currentLibrary,step:'items',item:null};render()};for(let x=0;x<(i.storage_paths||[]).length;x++){const{data}=sb.storage.from('public-materials').getPublicUrl(i.storage_paths[x]),d=document.createElement('div');d.className='thumb';d.innerHTML=`<img src="${data.publicUrl}" alt="Photo publique ${x+1}"><span class="num">${x+1}</span>`;publicThumbs.appendChild(d)}reportBtn.onclick=()=>showToast('Signalement enregistré pour ce test')}
}
async function render(){if(currentView==='home')renderHome();else if(currentView==='courses')renderCourses();else if(currentView==='course')renderCourse();else if(currentView==='section')renderSection();else if(currentView==='session')await renderSession();else if(currentView==='capture')renderCapture();else if(currentView==='captured')await renderCaptured();else if(currentView==='organize')await renderOrganize();else if(currentView==='inbox')await renderInbox();else if(currentView==='files')await renderFiles();else if(currentView==='library')await renderLibrary();else if(currentView==='profile')renderProfile()}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;nativeInstallBtn.hidden=false});
installBtn.onclick=()=>{installSheet.classList.remove('hidden');installSheet.setAttribute('aria-hidden','false')};
document.querySelector('[data-close-sheet]').onclick=()=>installSheet.classList.add('hidden');
nativeInstallBtn.onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installSheet.classList.add('hidden')}};
window.addEventListener('online',()=>{offlineBanner.classList.add('hidden');bootstrapCloud()});window.addEventListener('offline',()=>offlineBanner.classList.remove('hidden'));if(!navigator.onLine)offlineBanner.classList.remove('hidden');
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
bootstrapCloud().finally(()=>render());