function renderCapture(){
  if(!state.captureDraft){state.captureDraft={id:uid(),photoIds:[],createdAt:now()};saveState()}
  captureIds=[...state.captureDraft.photoIds];
  app.innerHTML=`<div class="capture-screen"><div class="capture-head"><button id="closeCam">×</button><div class="capture-title">Capture rapide</div><span class="badge orange" id="captureCount">0 photo</span></div><div class="camera-stage"><video id="cameraVideo" autoplay playsinline muted></video><div class="camera-message">Aucune sélection de cours maintenant. Continuez à photographier.</div></div><div class="camera-controls"><div class="camera-tools"><button class="tool-btn" id="flipCam">↺ Caméra</button><button class="tool-btn" id="torchBtn">☀ Torche</button><button class="tool-btn" id="galleryBtn">＋ Galerie</button><input type="file" id="galleryInput" accept="image/*" multiple hidden></div><div class="zoom-row"><span>Zoom</span><input id="zoomRange" type="range" min="1" max="1" step="0.1" value="1"><span id="zoomLabel">1×</span></div><div class="shutter-row"><button class="tool-btn" id="finishCapture">Terminer</button><button class="shutter" id="shutter" aria-label="Prendre une photo"></button><span></span></div></div></div>`;setTimeout(startCamera,0);byId('closeCam').onclick=()=>{stopCamera();if(captureIds.length){state.inbox.unshift({id:state.captureDraft.id,title:'Capture interrompue',photoIds:[...captureIds],createdAt:state.captureDraft.createdAt});showToast('Photos gardées dans Inbox')}state.captureDraft=null;captureIds=[];saveState();queueSync();navigate('home')};byId('shutter').onclick=capturePhoto;byId('flipCam').onclick=async()=>{cameraFacing=cameraFacing==='environment'?'user':'environment';await startCamera()};byId('torchBtn').onclick=toggleTorch;byId('galleryBtn').onclick=()=>byId('galleryInput').click();byId('galleryInput').onchange=importGallery;byId('finishCapture').onclick=finishCapture;byId('zoomRange').oninput=applyZoom;byId('captureCount').textContent=`${captureIds.length} photo${captureIds.length>1?'s':''}`;
}
async function startCamera(){stopCamera();const video=document.getElementById('cameraVideo');if(!video)return;try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:cameraFacing},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=cameraStream;cameraTrack=cameraStream.getVideoTracks()[0];const caps=cameraTrack.getCapabilities?.()||{},zr=document.getElementById('zoomRange'),tb=document.getElementById('torchBtn');if(caps.zoom&&zr){zr.min=caps.zoom.min;zr.max=caps.zoom.max;zr.step=caps.zoom.step||.1;zr.value=Math.max(caps.zoom.min,Math.min(1,caps.zoom.max));zoomValue=Number(zr.value);byId('zoomLabel').textContent=`${zoomValue.toFixed(1)}×`}else if(zr){zr.disabled=true;byId('zoomLabel').textContent='Non dispo'}if(tb&&!caps.torch){tb.disabled=true;tb.textContent='Torche indisponible'}}catch(e){console.error(e);showToast('Autorisez la caméra dans Safari') }}
function stopCamera(){cameraStream?.getTracks?.().forEach(t=>t.stop());cameraStream=null;cameraTrack=null;torchOn=false}
async function applyZoom(e){if(!cameraTrack)return;zoomValue=Number(e.target.value);try{await cameraTrack.applyConstraints({advanced:[{zoom:zoomValue}]});byId('zoomLabel').textContent=`${zoomValue.toFixed(1)}×`}catch{}}
async function toggleTorch(){if(!cameraTrack)return;const caps=cameraTrack.getCapabilities?.()||{};if(!caps.torch){showToast('La torche n’est pas disponible dans ce navigateur');return}torchOn=!torchOn;try{await cameraTrack.applyConstraints({advanced:[{torch:torchOn}]});byId('torchBtn').classList.toggle('active',torchOn)}catch{showToast('Impossible d’activer la torche')}}
async function capturePhoto(){const video=document.getElementById('cameraVideo');if(!video?.videoWidth){showToast('La caméra n’est pas prête');return}const maxW=1800,scale=Math.min(1,maxW/video.videoWidth),c=document.createElement('canvas');c.width=Math.round(video.videoWidth*scale);c.height=Math.round(video.videoHeight*scale);c.getContext('2d').drawImage(video,0,0,c.width,c.height);const blob=await new Promise(res=>c.toBlob(res,'image/jpeg',.9));const id=uid();await DB.put('photos',{id,blob,createdAt:now(),syncState:'pending'});captureIds.push(id);state.captureDraft.photoIds=[...captureIds];saveState();byId('captureCount').textContent=`${captureIds.length} photo${captureIds.length>1?'s':''}`;navigator.vibrate?.(18)}
async function importGallery(e){for(const f of [...(e.target.files||[])]){const id=uid();await DB.put('photos',{id,blob:f,createdAt:now(),syncState:'pending'});captureIds.push(id)}state.captureDraft.photoIds=[...captureIds];saveState();byId('captureCount').textContent=`${captureIds.length} photo${captureIds.length>1?'s':''}`;e.target.value=''}
function finishCapture(){if(!captureIds.length){showToast('Prenez au moins une photo');return}stopCamera();currentBatch={id:state.captureDraft?.id||uid(),photoIds:[...captureIds],selected:new Set(captureIds),createdAt:state.captureDraft?.createdAt||now(),splitQueue:[]};state.captureDraft=null;captureIds=[];saveState();navigate('captureComplete')}
async function renderCaptureComplete(){
  if(!currentBatch){navigate('home');return}app.innerHTML=`${pageHead(`${currentBatch.photoIds.length} photo${currentBatch.photoIds.length>1?'s':''} capturée${currentBatch.photoIds.length>1?'s':''}`,'Que voulez-vous faire maintenant ?','CAPTURE TERMINÉE')}<div class="thumbs" id="capturedThumbs"></div><div class="actions"><button class="btn purple full" id="organizeNow">Organiser maintenant</button><button class="btn soft full" id="splitNow">Diviser le lot</button><button class="btn ghost full" id="saveInbox">Garder dans Inbox</button></div>`;await fillThumbs('capturedThumbs',currentBatch.photoIds,{selectable:false});byId('organizeNow').onclick=()=>{currentBatch.selected=new Set(currentBatch.photoIds);navigate('organize')};byId('splitNow').onclick=()=>{currentBatch.selected=new Set(currentBatch.photoIds.slice(0,Math.ceil(currentBatch.photoIds.length/2)));navigate('split')};byId('saveInbox').onclick=()=>saveBatchToInbox(currentBatch)
}
async function fillThumbs(containerId,ids,{selectable=false,split=false}={}){const box=document.getElementById(containerId);if(!box)return;box.innerHTML='';for(let i=0;i<ids.length;i++){const id=ids[i],url=await DB.blobUrl('photos',id),selected=currentBatch?.selected?.has(id),b=document.createElement('button');b.className=`thumb ${selectable&&selected?'selected':''} ${split?(selected?'group-a':'group-b'):''}`;b.innerHTML=`<img src="${url}" alt="Photo ${i+1}"><span class="num">${i+1}</span>${selectable&&!split?`<span class="check">${selected?'✓':''}</span>`:''}${split?`<span class="group-tag">${selected?'LOT 1':'LOT 2'}</span>`:''}`;if(selectable)b.onclick=()=>{selected?currentBatch.selected.delete(id):currentBatch.selected.add(id);render()};box.appendChild(b)}}
function saveBatchToInbox(batch){state.inbox.unshift({id:batch.id,title:`Capture ${fmtShort(batch.createdAt)}`,photoIds:[...batch.photoIds],createdAt:batch.createdAt});saveState();currentBatch=null;showToast('Lot enregistré dans Inbox');queueSync();navigate('home')}
async function renderSplit(){
  if(!currentBatch){navigate('home');return}const a=currentBatch.selected.size,b=currentBatch.photoIds.length-a;app.innerHTML=`${backButton()}${pageHead('Diviser le lot','Touchez les photos pour les déplacer entre Lot 1 et Lot 2.','SPLIT BATCH')}<div class="segmented"><button class="active">Lot 1 • ${a}</button><button>Lot 2 • ${b}</button></div><div class="spacer"></div><div class="thumbs" id="splitThumbs"></div><div class="actions"><button class="btn purple full" id="confirmSplit" ${!a||!b?'disabled':''}>Organiser les deux lots</button><button class="btn ghost full" id="splitInbox">Mettre les deux lots dans Inbox</button></div>`;byId('backBtn').onclick=()=>navigate('captureComplete');await fillThumbs('splitThumbs',currentBatch.photoIds,{selectable:true,split:true});byId('confirmSplit').onclick=()=>{const first=[...currentBatch.selected],second=currentBatch.photoIds.filter(id=>!currentBatch.selected.has(id));if(!first.length||!second.length)return;currentBatch={...currentBatch,photoIds:first,selected:new Set(first),splitQueue:[{id:uid(),photoIds:second,selected:new Set(second),createdAt:currentBatch.createdAt,splitQueue:[]}]};navigate('organize')};byId('splitInbox').onclick=()=>{const first=[...currentBatch.selected],second=currentBatch.photoIds.filter(id=>!currentBatch.selected.has(id));if(first.length)state.inbox.unshift({id:uid(),title:'Lot 1',photoIds:first,createdAt:currentBatch.createdAt});if(second.length)state.inbox.unshift({id:uid(),title:'Lot 2',photoIds:second,createdAt:currentBatch.createdAt});saveState();currentBatch=null;queueSync();navigate('inbox')}
}
async function renderOrganize(){
  if(!currentBatch){navigate('home');return}let c=getCourse();if(!c){c=state.courses[0];currentCourseId=c.id}ensureDefaultSections(c);let s=getSection(c);if(!s){s=c.sections.find(x=>x.name==='TD')||c.sections[0];currentSectionId=s.id}const next=(s.sessions.at(-1)?.number||0)+1;
  app.innerHTML=`${backButton()}${pageHead('Organiser les photos','Sélectionnez la destination de ce lot.','ORGANISER')}<div class="thumbs" id="organizeThumbs"></div><div class="spacer"></div><div class="field"><label>Cours</label><select id="orgCourse">${state.courses.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Section</label><select id="orgSection">${c.sections.map(x=>`<option value="${x.id}" ${x.id===s.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Titre de séance</label><input id="orgTitle" placeholder="${esc(s.name)} ${next}"></div><div class="notice">${currentBatch.photoIds.length} photo${currentBatch.photoIds.length>1?'s':''} seront enregistrées dans cette séance.</div><div class="actions"><button class="btn purple full" id="assignBatch">Enregistrer dans la séance</button><button class="btn ghost full" id="moveInbox">Garder ce lot dans Inbox</button></div>`;byId('backBtn').onclick=()=>navigate('captureComplete');await fillThumbs('organizeThumbs',currentBatch.photoIds,{selectable:false});byId('orgCourse').onchange=e=>{currentCourseId=e.target.value;currentSectionId=null;render()};byId('orgSection').onchange=e=>{currentSectionId=e.target.value;render()};byId('assignBatch').onclick=()=>assignCurrentBatch(byId('orgTitle').value);byId('moveInbox').onclick=()=>{const nextBatch=currentBatch.splitQueue?.shift();saveBatchToInbox(currentBatch);if(nextBatch){currentBatch=nextBatch;navigate('organize')}}
}
function assignCurrentBatch(customTitle){const c=getCourse(),s=getSection(c);if(!c||!s)return;const num=(s.sessions.at(-1)?.number||0)+1,q={id:uid(),number:num,title:customTitle.trim()||`${s.name} ${num}`,photoIds:[...currentBatch.photoIds],createdAt:now(),visibility:'private'};s.sessions.push(q);currentSessionId=q.id;const nextBatch=currentBatch.splitQueue?.shift()||null;saveState();queueSync();if(nextBatch){currentBatch=nextBatch;currentCourseId=null;currentSectionId=null;showToast('Lot 1 enregistré. Organisez maintenant le lot suivant.');navigate('organize')}else{currentBatch=null;navigate('session')}}
async function renderInbox(){
  app.innerHTML=`${pageHead('Inbox','Captures locales non classées. Elles restent disponibles hors ligne.','INBOX')}<div class="grid" id="inboxList"></div>`;if(!state.inbox.length){byId('inboxList').innerHTML='<div class="card empty"><div class="empty-icon">✓</div>Inbox est vide.</div>';return}for(const b of state.inbox){const el=document.createElement('button');el.className='card row card-button';el.innerHTML=`<span class="section-icon custom">${b.photoIds.length}</span><span class="grow"><span class="title">${esc(b.title||`Capture ${fmtShort(b.createdAt)}`)}</span><span class="meta">${b.photoIds.length} photo${b.photoIds.length>1?'s':''} • ${fmtDate(b.createdAt)}</span></span><span class="chev">›</span>`;el.onclick=()=>{state.inbox=state.inbox.filter(x=>x.id!==b.id);saveState();currentBatch={...b,selected:new Set(b.photoIds),splitQueue:[]};navigate('captureComplete')};byId('inboxList').appendChild(el)}}
