function renderWelcome(){
  setChrome(true);app.innerHTML=`<div class="onboarding-shell"><div><div class="onboarding-logo"><b>H</b><b>ol</b><b>io</b><b>o</b></div><h1 class="onboarding-title">Vos cours. Capturés, organisés, retrouvés.</h1><p class="onboarding-copy">Holioo enregistre d’abord sur votre appareil. Vous pouvez photographier sans choisir de cours, puis organiser vos captures après.</p><div class="feature-list"><div class="feature"><span>●</span><div><b>Capture immédiate</b><small>Aucun CM/TD/TP à sélectionner avant la photo.</small></div></div><div class="feature"><span>⌁</span><div><b>Local-first</b><small>Les photos restent disponibles même sans Internet.</small></div></div><div class="feature"><span>☁</span><div><b>Synchronisation</b><small>Quand Internet revient, Google Drive peut sauvegarder automatiquement.</small></div></div></div></div><div class="actions"><button class="btn primary full" id="welcomeStart">Commencer</button><button class="btn ghost full" id="welcomeSkip">Utiliser hors ligne</button></div></div>`;
  byId('welcomeStart').onclick=()=>navigate('academicSetup');byId('welcomeSkip').onclick=()=>{state.onboardingComplete=true;state.academicSetupSeen=true;saveState();navigate('home')};
}
function renderAcademicSetup(){
  const p=state.profile;app.innerHTML=`<div class="onboarding-shell"><div>${pageHead('Profil académique','Facultatif — vous pourrez tout changer plus tard.','CONFIGURATION')}<div class="field"><label>Université</label><input id="acUni" value="${esc(p.university)}" placeholder="Ex. Sorbonne Université"></div><div class="field"><label>Faculté</label><input id="acFaculty" value="${esc(p.faculty)}" placeholder="Ex. Sciences & Ingénierie"></div><div class="field"><label>Filière / majeure</label><input id="acProgram" value="${esc(p.program)}" placeholder="Ex. EEA"></div><div class="grid two"><div class="field"><label>Niveau</label><input id="acLevel" value="${esc(p.level)}" placeholder="L2"></div><div class="field"><label>Semestre</label><input id="acSem" value="${esc(p.semester)}" placeholder="S3"></div></div><div class="field"><label>Année universitaire</label><input id="acYear" value="${esc(p.academicYear)}" placeholder="2026–2027"></div></div><div class="actions"><button class="btn primary full" id="saveAcademic">Continuer</button><button class="btn ghost full" id="skipAcademic">Passer pour le moment</button></div></div>`;
  byId('saveAcademic').onclick=async()=>{Object.assign(state.profile,{university:byId('acUni').value.trim(),faculty:byId('acFaculty').value.trim(),program:byId('acProgram').value.trim(),level:byId('acLevel').value.trim(),semester:byId('acSem').value.trim(),academicYear:byId('acYear').value.trim()||'2026–2027'});state.onboardingComplete=true;state.academicSetupSeen=true;saveState();try{await syncProfile()}catch{}navigate('home')};byId('skipAcademic').onclick=()=>{state.onboardingComplete=true;state.academicSetupSeen=true;saveState();navigate('home')};
}
async function renderHome(){
  setChrome(false);const sessionCount=state.courses.reduce((a,c)=>a+c.sections.reduce((x,s)=>x+s.sessions.length,0),0),inboxCount=state.inbox.reduce((a,b)=>a+b.photoIds.length,0),fileCount=state.files.length;let pending=0;try{pending=await Drive.pendingCount(state,DB)}catch{}
  app.innerHTML=`${pageHead(`Bonjour${state.profile.displayName&&state.profile.displayName!=='Étudiant'?` ${state.profile.displayName}`:''} 👋`,'Capturez maintenant. Organisez quand vous avez le temps.','ACCUEIL')}<div class="hero-card"><p class="hero-title">Ne ratez plus une page de cours.</p><p class="meta">Capture rapide, classement après le cours, PDF en quelques secondes.</p><button class="btn orange" data-nav="capture" style="margin-top:14px">Ouvrir la caméra</button></div><div class="section-title">Aperçu</div><div class="stats"><div class="stat"><b>${sessionCount}</b><span>Séances</span></div><div class="stat"><b>${inboxCount}</b><span>Inbox</span></div><div class="stat"><b>${fileCount}</b><span>PDF</span></div></div><div class="section-title">Capture rapide</div><button class="card quick-capture card-button" data-nav="capture"><span class="quick-icon">●</span><span class="grow"><span class="title">Prendre des photos</span><span class="meta">Sans choisir CM, TD ou TP</span></span><span class="chev">›</span></button>${state.inbox.length?`<div class="section-title">À organiser</div><button class="card row card-button" id="openInbox"><span class="section-icon custom">I</span><span class="grow"><span class="title">Inbox</span><span class="meta">${inboxCount} photo${inboxCount>1?'s':''} en attente</span></span><span class="badge orange">À classer</span></button>`:''}<div class="section-title">Vos cours</div><div class="grid">${state.courses.slice(0,4).map(courseCard).join('')}</div><div class="section-title">Sauvegarde</div><button class="card row card-button sync-card" data-nav="sync"><span class="round-icon" style="background:${driveStatus.connected?'#24B27D':'#506BFF'}">☁</span><span class="grow"><span class="title">${driveStatus.connected?'Google Drive connecté':'Synchronisation Google Drive'}</span><span class="meta">${driveStatus.connected?`${pending} élément(s) restant(s) • ${esc(driveStatus.email||'compte connecté')}`:'Sauvegardez vos photos dans le Drive de chaque utilisateur.'}</span></span><span class="chev">›</span></button>`;
  bindCourseCards();document.getElementById('openInbox')?.addEventListener('click',()=>navigate('inbox'));
}
function renderCourses(){
  app.innerHTML=`${pageHead('Cours','Chaque cours possède automatiquement CM, TD, TP et peut contenir autant de sections personnalisées que nécessaire.','COURS')}<div class="grid">${state.courses.map(courseCard).join('')}</div><div class="actions"><button class="btn primary full" id="addCourse">+ Ajouter un cours</button></div>`;bindCourseCards();byId('addCourse').onclick=()=>openSheet({title:'Nouveau cours',subtitle:'Vous pourrez ajouter des sections et séances ensuite.',body:'<div class="field"><label>Nom du cours</label><input id="newCourseName" placeholder="Ex. Traitement du signal"></div>',onConfirm:()=>{const name=document.getElementById('newCourseName').value.trim();if(!name){showToast('Entrez un nom de cours');return false}const colors=['#506BFF','#8C5CF5','#FF9E42','#29ADB5'];state.courses.push(sampleCourse(name,colors[state.courses.length%colors.length]));saveState();render();queueSync();return true}})
}
function renderCourse(){
  const c=getCourse();if(!c){navigate('courses');return}ensureDefaultSections(c);saveState();app.innerHTML=`${backButton()}${pageHead(c.name,'CM, TD, TP et sections personnalisées.','COURS')}<div class="grid">${c.sections.map(s=>`<button class="card row card-button" data-section="${s.id}"><span class="section-icon ${sectionClass(s.name)}">${esc(iconLetter(s.name))}</span><span class="grow"><span class="title">${esc(s.name)}</span><span class="meta">${s.sessions.length} séance${s.sessions.length>1?'s':''}</span></span><span class="chev">›</span></button>`).join('')}</div><div class="actions"><button class="btn ghost full" id="addSection">+ Ajouter une section personnalisée</button></div>`;byId('backBtn').onclick=()=>navigate('courses');document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{currentSectionId=b.dataset.section;navigate('section')});byId('addSection').onclick=()=>openSheet({title:'Section personnalisée',subtitle:'Projet, Révision, Examen, Tutorial, Lab…',body:'<div class="field"><label>Nom de la section</label><input id="sectionName" placeholder="Ex. Projet"></div>',confirmClass:'teal',onConfirm:()=>{const n=byId('sectionName').value.trim();if(!n)return false;c.sections.push({id:uid(),name:n,type:'CUSTOM',sortOrder:c.sections.length,sessions:[]});saveState();render();return true}})
}
function renderSection(){
  const c=getCourse(),s=getSection(c);if(!c||!s){navigate('courses');return}app.innerHTML=`${backButton()}${pageHead(`${c.name} • ${s.name}`,'La numérotation est indépendante dans chaque section.','SÉANCES')}<div class="grid">${s.sessions.length?s.sessions.map(q=>`<button class="card row card-button" data-session="${q.id}"><span class="section-icon ${sectionClass(s.name)}">${q.number||'•'}</span><span class="grow"><span class="title">${esc(q.title)}</span><span class="meta">${q.photoIds?.length||0} photo${(q.photoIds?.length||0)>1?'s':''} • ${fmtShort(q.createdAt)}</span></span>${q.visibility==='public'?'<span class="badge teal">PUBLIC</span>':''}<span class="chev">›</span></button>`).join(''):'<div class="card empty"><div class="empty-icon">▤</div>Aucune séance pour le moment.</div>'}</div><div class="actions"><button class="btn purple full" id="newSession">+ Nouvelle séance</button></div>`;byId('backBtn').onclick=()=>navigate('course');document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{currentSessionId=b.dataset.session;navigate('session')});byId('newSession').onclick=()=>{const num=(s.sessions.at(-1)?.number||0)+1;openSheet({title:`Nouvelle séance ${s.name}`,subtitle:`Le titre automatique sera « ${s.name} ${num} ».`,body:`<div class="field"><label>Titre personnalisé (facultatif)</label><input id="sessionTitle" placeholder="${esc(s.name)} ${num} — sujet"></div>`,confirmClass:'purple',onConfirm:()=>{const q={id:uid(),number:num,title:byId('sessionTitle').value.trim()||`${s.name} ${num}`,photoIds:[],createdAt:now(),visibility:'private'};s.sessions.push(q);saveState();currentSessionId=q.id;navigate('session');return true}})}}
async function renderSession(){
  const ctx=findSessionContext();if(!ctx){navigate('courses');return}const{course,section,session}=ctx;app.innerHTML=`${backButton()}${pageHead(session.title,`${course.name} • ${section.name} • ${session.photoIds.length} photo${session.photoIds.length>1?'s':''}`,'SÉANCE')}${session.photoIds.length?`<div class="gallery-head"><div><b>Galerie</b><span> Touchez une photo pour l’ouvrir en plein écran.</span></div><button class="chip" id="openFirstPhoto">Plein écran</button></div><div class="thumbs" id="sessionThumbs"></div><div class="actions"><button class="btn primary full" id="buildPdf">Créer un PDF</button><button class="btn teal full" id="publishSession">${session.visibility==='public'?'Publié dans la bibliothèque ✓':'Publier dans la bibliothèque académique'}</button><button class="btn ghost full" id="renameSession">Renommer la séance</button></div>`:`<div class="card empty"><div class="empty-icon">●</div>Cette séance ne contient pas encore de photos.</div><div class="actions"><button class="btn orange full" data-nav="capture">Prendre des photos</button></div>`}`;byId('backBtn').onclick=()=>navigate('section');if(session.photoIds.length){await fillSessionThumbs(session);byId('openFirstPhoto').onclick=()=>openPhotoViewer(session.photoIds,0,{title:session.title,source:'session',sourceId:session.id,editable:true,returnView:'session',courseId:course.id,sectionId:section.id,sessionId:session.id})}document.getElementById('buildPdf')?.addEventListener('click',()=>navigate('pdfBuilder'));document.getElementById('publishSession')?.addEventListener('click',()=>publishSession(course,section,session));document.getElementById('renameSession')?.addEventListener('click',()=>openSheet({title:'Renommer la séance',body:`<div class="field"><label>Titre</label><input id="renameValue" value="${esc(session.title)}"></div>`,onConfirm:()=>{session.title=byId('renameValue').value.trim()||session.title;saveState();render();queueSync();return true}}))
}
async function fillSessionThumbs(session){
  const box=document.getElementById('sessionThumbs');if(!box)return;box.innerHTML='';
  const ctx=findSessionContext(session.id);
  for(let i=0;i<session.photoIds.length;i++){
    const id=session.photoIds[i],row=await DB.get('photos',id);if(!row?.blob)continue;const url=URL.createObjectURL(row.blob),status=photoStatusLabel(row),d=document.createElement('div');d.className='thumb gallery-thumb';
    d.innerHTML=`<img src="${url}" alt="Photo ${i+1}" data-open-photo="${i}"><span class="num">${i+1}</span><span class="thumb-status badge ${status.cls}">${status.label}</span><div class="thumb-actions"><button data-left="${id}" aria-label="Déplacer à gauche">←</button><button data-right="${id}" aria-label="Déplacer à droite">→</button><button data-move="${id}" aria-label="Déplacer vers une autre séance">↗</button><button data-del="${id}" aria-label="Supprimer">×</button></div>`;
    d.querySelector('[data-open-photo]').onclick=()=>openPhotoViewer(session.photoIds,i,{title:session.title,source:'session',sourceId:session.id,editable:true,returnView:'session',courseId:ctx?.course.id,currentSectionId:ctx?.section.id,sectionId:ctx?.section.id,sessionId:session.id});
    box.appendChild(d);
  }
  box.querySelectorAll('[data-left]').forEach(b=>b.onclick=e=>{e.stopPropagation();movePhoto(session,b.dataset.left,-1)});
  box.querySelectorAll('[data-right]').forEach(b=>b.onclick=e=>{e.stopPropagation();movePhoto(session,b.dataset.right,1)});
  box.querySelectorAll('[data-move]').forEach(b=>b.onclick=e=>{e.stopPropagation();movePhotoToSession(session,b.dataset.move)});
  box.querySelectorAll('[data-del]').forEach(b=>b.onclick=e=>{e.stopPropagation();deleteSessionPhoto(session,b.dataset.del)});
}
function movePhotoToSession(sourceSession,photoId){
  const targets=[];for(const course of state.courses)for(const section of course.sections)for(const session of section.sessions)if(session.id!==sourceSession.id)targets.push({course,section,session});
  if(!targets.length){showToast('Créez d’abord une autre séance');return}
  openSheet({title:'Déplacer la photo',subtitle:'Choisissez la séance de destination.',body:`<div class="field"><label>Destination</label><select id="moveTarget">${targets.map(t=>`<option value="${t.session.id}">${esc(t.course.name)} • ${esc(t.section.name)} • ${esc(t.session.title)}</option>`).join('')}</select></div>`,confirmText:'Déplacer',confirmClass:'purple',onConfirm:()=>{const id=byId('moveTarget').value,target=targets.find(t=>t.session.id===id);if(!target)return false;sourceSession.photoIds=sourceSession.photoIds.filter(x=>x!==photoId);target.session.photoIds.push(photoId);saveState();queueSync();render();showToast('Photo déplacée');return true}})
}
function movePhoto(session,id,dir){const i=session.photoIds.indexOf(id),j=i+dir;if(i<0||j<0||j>=session.photoIds.length)return;[session.photoIds[i],session.photoIds[j]]=[session.photoIds[j],session.photoIds[i]];saveState();render();queueSync()}
async function deleteSessionPhoto(session,id){openSheet({title:'Supprimer la photo ?',subtitle:'Elle sera supprimée de Holioo sur cet appareil. Une copie déjà synchronisée dans Drive peut rester jusqu’à suppression manuelle.',confirmText:'Supprimer',confirmClass:'coral',onConfirm:async()=>{session.photoIds=session.photoIds.filter(x=>x!==id);await DB.del('photos',id);saveState();render();return true}})}
