function renderPdfBuilder(){
  const ctx=findSessionContext();if(!ctx){navigate('files');return}const{course,session}=ctx;const allSessions=course.sections.flatMap(s=>s.sessions.map(q=>({section:s,session:q}))).filter(x=>x.session.photoIds.length);const pre=new Set([session.id]);app.innerHTML=`${backButton()}${pageHead('Créer un PDF','Sélectionnez une ou plusieurs séances du même cours.','PDF')}<div class="field"><label>Titre du document</label><input id="pdfTitle" value="${esc(`${course.name} — ${session.title}`)}"></div><div class="section-title">Séances</div><div class="grid">${allSessions.map(({section,session:q})=>`<label class="card row"><input type="checkbox" class="pdfSession" value="${q.id}" ${pre.has(q.id)?'checked':''}><span class="section-icon ${sectionClass(section.name)}">${q.number}</span><span class="grow"><span class="title">${esc(q.title)}</span><span class="meta">${esc(section.name)} • ${q.photoIds.length} photos</span></span></label>`).join('')}</div><div class="section-title">Mise en page</div><div class="pdf-options"><label class="card toggle-row"><input type="checkbox" id="pdfCover" checked><span><b>Page de couverture</b><span class="meta">Cours, année universitaire et titre</span></span></label><label class="card toggle-row"><input type="checkbox" id="pdfToc" checked><span><b>Table des matières</b><span class="meta">Sections et séances</span></span></label><label class="card toggle-row"><input type="checkbox" id="pdfNumbers" checked><span><b>Numéros de page</b><span class="meta">Ajoutés en pied de page</span></span></label></div><div class="actions"><button class="btn primary full" id="generatePdf">Générer le PDF</button></div>`;byId('backBtn').onclick=()=>navigate('session');byId('generatePdf').onclick=async()=>{const ids=[...document.querySelectorAll('.pdfSession:checked')].map(x=>x.value);if(!ids.length){showToast('Sélectionnez au moins une séance');return}await generatePdfFile(course,ids,{title:byId('pdfTitle').value.trim()||course.name,cover:byId('pdfCover').checked,toc:byId('pdfToc').checked,numbers:byId('pdfNumbers').checked})}
}
async function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
async function generatePdfFile(course,sessionIds,opts){
  if(!window.jspdf){showToast('Le module PDF n’est pas disponible');return}showToast('Création du PDF…');try{const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'});let hasPage=false,pageNo=0;const entries=[];for(const section of course.sections)for(const q of section.sessions)if(sessionIds.includes(q.id))entries.push({section,session:q});
    const addPage=()=>{if(hasPage)doc.addPage();hasPage=true;pageNo++};
    if(opts.cover){addPage();doc.setFont('helvetica','bold');doc.setFontSize(26);doc.text(course.name,20,38);doc.setFontSize(17);doc.text(opts.title,20,54,{maxWidth:170});doc.setFont('helvetica','normal');doc.setFontSize(11);doc.text(state.profile.academicYear||'',20,70);doc.text([state.profile.university,state.profile.program,state.profile.level,state.profile.semester].filter(Boolean).join(' • '),20,80,{maxWidth:170})}
    if(opts.toc){addPage();doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Table des matières',20,28);doc.setFont('helvetica','normal');doc.setFontSize(11);let y=45;for(const e of entries){doc.text(`${e.section.name} — ${e.session.title}`,20,y,{maxWidth:165});y+=9;if(y>270){addPage();y=25}}}
    for(const e of entries){for(let i=0;i<e.session.photoIds.length;i++){const p=await DB.get('photos',e.session.photoIds[i]);if(!p?.blob)continue;addPage();const data=await blobToDataURL(p.blob),props=doc.getImageProperties(data),ratio=Math.min(178/props.width,245/props.height),w=props.width*ratio,h=props.height*ratio;doc.addImage(data,'JPEG',(210-w)/2,16,w,h,undefined,'FAST');doc.setFontSize(8);doc.setTextColor(85);doc.text(`${course.name} • ${e.section.name} • ${e.session.title}`,14,286,{maxWidth:165});if(opts.numbers)doc.text(String(pageNo),196,286,{align:'right'});doc.setTextColor(0)}}
    if(!hasPage)addPage();const blob=doc.output('blob'),id=uid(),fileName=`${Drive.safeName(opts.title)}.pdf`;await DB.put('files',{id,blob,createdAt:now(),syncState:'pending'});state.files.unshift({id,title:opts.title,fileName,courseId:course.id,sessionIds,createdAt:now(),pages:pageNo});saveState();queueSync();const file=new File([blob],fileName,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:opts.title,files:[file]});else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=fileName;a.click()}showToast('PDF créé');navigate('files')
  }catch(e){console.error(e);showToast('Erreur pendant la création du PDF')}
}
async function renderFiles(){
  app.innerHTML=`${pageHead('Fichiers','PDF créés sur cet appareil. Ils peuvent aussi être synchronisés vers Google Drive.','FICHIERS')}<div class="grid" id="fileList"></div>`;if(!state.files.length){byId('fileList').innerHTML='<div class="card empty"><div class="empty-icon">▱</div>Aucun PDF pour le moment.</div>';return}for(const f of state.files){const row=await DB.get('files',f.id),el=document.createElement('button');el.className='card row card-button';el.innerHTML=`<span class="pdf-icon">PDF</span><span class="grow"><span class="title">${esc(f.title)}</span><span class="meta">${f.pages||'—'} pages • ${fmtDate(f.createdAt)}</span></span><span class="badge ${row?.driveFileId?'green':'gray'}">${row?.driveFileId?'DRIVE':'LOCAL'}</span><span class="chev">›</span>`;el.onclick=async()=>{if(!row?.blob)return;const file=new File([row.blob],f.fileName||`${f.title}.pdf`,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]}))navigator.share({title:f.title,files:[file]});else window.open(URL.createObjectURL(row.blob),'_blank')};byId('fileList').appendChild(el)}}
