'use strict';

async function publishSession(course,section,session){
  if(session.visibility==='public'){showToast('Cette séance est déjà publique');return}if(!navigator.onLine||!sb||!currentUser){showToast('Internet est nécessaire pour publier');return}const p=state.profile;if(!p.university||!p.program||!p.level||!p.semester||!p.academicYear){showToast('Complétez votre profil académique');navigate('profile');return}
  openSheet({title:'Publier cette séance ?',subtitle:'Les photos deviendront visibles dans la bibliothèque académique correspondante.',body:'<div class="notice">Vérifiez qu’aucun visage, nom, adresse ou information personnelle d’une autre personne n’est visible.</div>',confirmText:'Publier',confirmClass:'teal',onConfirm:async()=>{try{const paths=[];for(let i=0;i<session.photoIds.length;i++){const ph=await DB.get('photos',session.photoIds[i]);if(!ph?.blob)continue;const path=`${currentUser.id}/${session.id}/${i+1}.jpg`;const{error}=await sb.storage.from('public-materials').upload(path,ph.blob,{contentType:'image/jpeg',upsert:true});if(error)throw error;paths.push(path)}const{error}=await sb.from('public_materials').insert({owner_id:currentUser.id,session_local_id:session.id,title:session.title,type:'Photos',photo_count:paths.length,storage_paths:paths,university:p.university,faculty:p.faculty||'',program:p.program,level:p.level,semester:p.semester,academic_year:p.academicYear,course:course.name,section:section.name,contributor_name:p.publicProfile?p.displayName:null,contributor_holioo_id:p.publicProfile?p.holiooId:null,is_published:true});if(error)throw error;session.visibility='public';saveState();showToast('Séance publiée');render();return true}catch(e){console.error(e);showToast('Publication impossible');return false}}})
}

function libraryQuery(columns='*'){const p=state.profile;return sb.from('public_materials').select(columns).eq('is_published',true).eq('university',p.university).eq('program',p.program).eq('level',p.level).eq('semester',p.semester).eq('academic_year',currentLibrary.year)}

async function connectDrive(){
  if(!navigator.onLine||!sb){showToast('Internet est nécessaire');return}
  const popup=window.open('about:blank','_blank');
  try{const data=await Drive.connect(sb);if(!data?.auth_url)throw new Error('Lien Google indisponible');if(popup)popup.location.href=data.auth_url;else location.href=data.auth_url;showToast('Autorisez Holioo dans la fenêtre Google');clearInterval(drivePollTimer);drivePollTimer=setInterval(async()=>{try{const s=await Drive.status(sb,currentUser.id);if(s.connected){clearInterval(drivePollTimer);driveStatus=s;showToast('Google Drive connecté');await refreshSyncIndicator();render();queueSync('connected')}}catch{}},2500)}catch(e){try{popup?.close()}catch{}console.error(e);openSheet({title:'Google Drive n’est pas encore activé',subtitle:'Le bouton est prêt, mais les identifiants OAuth Google doivent être ajoutés au projet Holioo.',body:`<div class="notice">Erreur : ${esc(e.message||e)}</div><p class="small">Callback déjà préparé : ${esc(`${SUPABASE_URL}/functions/v1/drive-auth-callback`)}</p>`,confirmText:'Fermer',secondaryText:''})}}

async function disconnectDrive(){openSheet({title:'Déconnecter Google Drive ?',subtitle:'Les copies déjà présentes dans Drive ne seront pas supprimées.',confirmText:'Déconnecter',confirmClass:'coral',onConfirm:async()=>{try{await Drive.disconnect(sb);driveStatus={connected:false,email:null};await refreshSyncIndicator();render();showToast('Google Drive déconnecté');return true}catch(e){showToast('Impossible de déconnecter');return false}}})}

function showInstallSheet(){openSheet({title:'Installer Holioo sur iPhone',subtitle:'Ouvrez cette page dans Safari.',body:'<div class="notice">Touchez Partager → Sur l’écran d’accueil → Ajouter. Holioo s’ouvrira ensuite comme une app.</div>',confirmText:deferredInstallPrompt?'Installer maintenant':'Compris',onConfirm:async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null}return true},secondaryText:''})}